USE sdi;
DROP TABLE if exists stdpop;

CREATE TABLE stdpop (
	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	WEEK DATE,
	PATIENT_ZIP3 VARCHAR(3),
	AGEGROUP VARCHAR(12),
	SERVICE_PLACE VARCHAR(30),
	ILI_m INT,
	RSV_m INT,
	POPSTAT INT,
	ANY_DIAG_VISIT_CT INT
);	
	
